// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbGgPCkvdHc3Qk2tV0w8hio37tyyAPIH8',
    appId: '1:671685783620:web:4219fff7b028dabe8f4c11',
    messagingSenderId: '671685783620',
    projectId: 'lifevision-a8776',
    authDomain: 'lifevision-a8776.firebaseapp.com',
    databaseURL: 'https://lifevision-a8776-default-rtdb.firebaseio.com',
    storageBucket: 'lifevision-a8776.appspot.com',
    measurementId: 'G-26GH4X90ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Z7Ya8iDM8SJSx8nBXGu1pJu9lZ8Lttc',
    appId: '1:671685783620:android:fcb8b9e8f1a79c108f4c11',
    messagingSenderId: '671685783620',
    projectId: 'lifevision-a8776',
    databaseURL: 'https://lifevision-a8776-default-rtdb.firebaseio.com',
    storageBucket: 'lifevision-a8776.appspot.com',
  );
}
